name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool

    - name: Configure the project
      run: ./configure

    - name: Build the project
      run: make

    - name: Run tests
      run: make check

    - name: Verify distribution
      run: make distcheck
